NAME="gc"
VERS="8.2.8"
DESC="Boehm-Demers-Weiser garbage collector"
CATG="lib dev"
UPST="https://github.com/ivmai/bdwgc.git"
DEPS=()

SOURCE="${UPST%.git}/releases/download/v$VERS/gc-$VERS.tar.gz"
EXTRA=()

2b() {

cfg --enable-cplusplus
mk
mi

}
