NAME="libksba"
VERS="1.6.7"
DESC="Library for working with X.509 certificates, CMS data and related objects"
CATG="lib"
UPST="https://github.com/gpg/libksba.git"
DEPS=(
    "libgpg-error"
)

SOURCE="https://www.gnupg.org/ftp/gcrypt/$NAME/$NAME-$VERS.tar.bz2"
EXTRA=()

2b() {

cfg
mk
mi

}
