NAME="direnv"
VERS="2.36.0"
DESC="Utility for directory specific environments"
CATG="utils cli"
UPST="https://github.com/$NAME/$NAME.git"
DEPS=(
    "go"
)

SOURCE="${UPST%.git}/archive/refs/tags/v$VERS.tar.gz"
EXTRA=()

2b() {

mk
mi PREFIX=/usr

}
