NAME="lzo"
VERS="2.10"
DESC="Real-time (de)compression library favoring speed"
CATG="lib"
UPST="" # dead
SKIP_FETCH_VERSION=1
DEPS=()

SOURCE="http://www.oberhumer.com/opensource/lzo/download/lzo-$VERS.tar.gz"
EXTRA=()

2b() {

cfg --enable-shared
mk
mi

}
