NAME="evtest"
VERS="3fe3ce98d81ae8b00156933ddb86b92a874cba6a"
DESC="Kernel evdev device information and monitor"
CATG="utils"
UPST="https://gitlab.freedesktop.org/libevdev/evtest.git"
DEPS=()

SOURCE="https://gitlab.freedesktop.org/libevdev/evtest/-/archive/$VERS/evtest-$VERS.tar.bz2"
EXTRA=()

2b() {

./autogen.sh
cfg
mk
mi

}
