NAME="npth"
VERS="1.8"
DESC="The new GNU portable threads library"
CATG="lib"
UPST="https://github.com/gpg/npth.git"
DEPS=()

SOURCE="https://www.gnupg.org/ftp/gcrypt/npth/npth-$VERS.tar.bz2"
EXTRA=()

2b() {

cfg
mk
mi

}
