NAME="go"
VERS="1.24.2"
DESC="The Go programming langueage"
CATG="lang dev"
UPST="https://github.com/golang/go.git"
DEPS=()

SOURCE="https://go.dev/dl/go$VERS.linux-amd64.tar.gz"
EXTRA=()

2b() {

mkdir -pv "$D"
tar xf "$SRC/go$VERS.linux-amd64.tar.gz" -C "$D"

}
