NAME="xdg-dbus-proxy"
VERS="0.1.6"
DESC="Filtering proxy for dbus connections"
CATG="utils"
UPST="https://github.com/flatpak/$NAME.git"
DEPS=(
    "glib"
)

SOURCE="${UPST%.git}/releases/download/$VERS/$NAME-$VERS.tar.xz"
EXTRA=()

2b() {

with meson ninja

ms
nj
ni

}
