NAME="libseccomp"
VERS="2.6.0"
DESC="Easy, platform independent interface to the Linux kernel's syscall filtering mechanism."
CATG="lib"
UPST="https://github.com/seccomp/libseccomp.git"
DEPS=()

SOURCE="https://github.com/seccomp/libseccomp/releases/download/v$VERS/libseccomp-$VERS.tar.gz"
EXTRA=()

2b() {

cfg
mk
mi

}
